version: 2
jobs:
  check_for_updates:
    docker:
      - image: alpine:latest
    steps:
      - checkout # check out the code in the project directory
      - run: apk add bash curl
      - run: bash -c 'diff aws-landing-zone-initiation.template <(curl -s https://s3.amazonaws.com/solutions-reference/aws-landing-zone/latest/aws-landing-zone-initiation.template)'

workflows:
  version: 2
  commit:
    jobs:
      - check_for_updates

  weekdays:
    jobs:
      - check_for_updates
    triggers:
      - schedule:
          cron: '0 15 * * 1-5'
          filters:
            branches:
              only:
                - master

notify:
  when: on_fail
  webhooks:
    - url: https://outlook.office.com/webhook/d44f416b-fda6-451e-b555-7ea7e77b58b7@a3198c8c-0642-4649-849d-daacc3298f83/CircleCI/00694d46cbaa4bdf9ce306ddfd1e0ba7/3938c997-dec0-455f-a135-deae8a68615d
